# Generated by Django 5.2.9 on 2026-02-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="user",
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
        migrations.DeleteModel(
            name="UserSubscription",
        ),
    ]
