# Generated by Django 5.2.9 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="interval",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                max_length=10,
            ),
        ),
    ]
