# Generated by Django 5.2.12 on 2026-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_usersubscription_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="stripe_plan_id",
            new_name="stripe_price_id",
        ),
    ]
