# Generated by Django 5.2.17 on 2026-08-27 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_usersubscription_trial_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Stripe price IDs start with 'price_' (not a product ID, which starts with 'prod_').",
                        regex="^price_",
                    )
                ],
            ),
        ),
    ]
