# Generated by Django 5.2.9 on 2026-01-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameworld",
            name="latitude",
            field=models.FloatField(default=51.5074),
        ),
        migrations.AddField(
            model_name="gameworld",
            name="longitude",
            field=models.FloatField(default=-0.1278),
        ),
        migrations.AddField(
            model_name="gameworld",
            name="timezone",
            field=models.CharField(default="Europe/London", max_length=50),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="years_diff",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DailySunTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sunrise", models.DateTimeField()),
                ("sunset", models.DateTimeField()),
                ("dawn", models.DateTimeField()),
                ("dusk", models.DateTimeField()),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sun_times",
                        to="gameworld.gameworld",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("world", "date")},
            },
        ),
    ]
