# Generated by Django 5.2.8 on 2025-12-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0012_dailystats_gameworld_delete_gamecalendar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherevent",
            name="location",
        ),
    ]
