# Generated by Django 5.2.8 on 2025-12-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0013_remove_weatherevent_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameworld",
            name="highest_login_streak_current",
        ),
        migrations.RemoveField(
            model_name="gameworld",
            name="highest_login_streak_ever",
        ),
        migrations.RemoveField(
            model_name="gameworld",
            name="num_profiles",
        ),
        migrations.RemoveField(
            model_name="gameworld",
            name="total_activity_num",
        ),
        migrations.RemoveField(
            model_name="gameworld",
            name="total_activity_time",
        ),
        migrations.AddField(
            model_name="gameworld",
            name="latitude",
            field=models.FloatField(default=51.5074),
        ),
        migrations.AddField(
            model_name="gameworld",
            name="longitude",
            field=models.FloatField(default=-0.1278),
        ),
        migrations.AddField(
            model_name="gameworld",
            name="timezone",
            field=models.CharField(default="Europe/London", max_length=50),
        ),
        migrations.CreateModel(
            name="DailySunTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sunrise", models.DateTimeField()),
                ("sunset", models.DateTimeField()),
                ("dawn", models.DateTimeField()),
                ("dusk", models.DateTimeField()),
                ("nautical_dawn", models.DateTimeField()),
                ("nautical_dusk", models.DateTimeField()),
                ("astronomical_dawn", models.DateTimeField()),
                ("astronomical_dusk", models.DateTimeField()),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sun_times",
                        to="gameworld.gameworld",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("world", "date")},
            },
        ),
    ]
