# Generated by Django 5.2.8 on 2025-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0014_remove_gameworld_highest_login_streak_current_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameworld",
            name="years_diff",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
