# Generated by Django 5.2.8 on 2025-12-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0015_alter_gameworld_years_diff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailysuntimes",
            name="astronomical_dawn",
        ),
        migrations.RemoveField(
            model_name="dailysuntimes",
            name="astronomical_dusk",
        ),
        migrations.RemoveField(
            model_name="dailysuntimes",
            name="nautical_dawn",
        ),
        migrations.RemoveField(
            model_name="dailysuntimes",
            name="nautical_dusk",
        ),
    ]
