# Generated by Django 5.2.8 on 2025-12-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0016_remove_dailysuntimes_astronomical_dawn_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyStats",
        ),
    ]
