# Generated by Django 5.2.9 on 2026-02-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_current_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
