# Generated by Django 5.2.9 on 2026-02-12 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_subscription_current_period_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="player",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="player",
            name="login_streak",
        ),
        migrations.RemoveField(
            model_name="player",
            name="login_streak_max",
        ),
        migrations.RemoveField(
            model_name="player",
            name="total_logins",
        ),
        migrations.AddField(
            model_name="player",
            name="active_connections",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("earned", models.PositiveIntegerField(default=0)),
                ("spent", models.PositiveIntegerField(default=0)),
                ("last_calculated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "name")},
            },
        ),
    ]
