# Generated by Django 5.2.9 on 2026-03-13 22:08

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_playercurrency_currency_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
    ]
