# Generated by Django 5.2.12 on 2026-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_player_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
