# Generated by Django 5.2.16 on 2026-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_waitlist_nudge_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="link_points_multiplier",
            field=models.DecimalField(decimal_places=2, default="1.00", max_digits=5),
        ),
    ]
