# Generated by Django 5.2.17 on 2026-08-19 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_player_link_points_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="day_start_time",
            field=models.TimeField(default=datetime.time(2, 0)),
        ),
        migrations.AddField(
            model_name="userlogin",
            name="logical_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
