# Generated by Django 5.2.17 on 2026-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_backfill_userlogin_logical_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialstep",
            name="unlock_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("infobar", "Infobar"),
                    ("library", "Library"),
                    ("map", "Map"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
