# Generated by Django 5.2.17 on 2026-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_backfill_userlogin_logical_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="inactivity_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="receives_inactivity_reminder",
            field=models.BooleanField(default=True),
        ),
    ]
