# Generated by Django 5.2.17 on 2026-08-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_backfill_userlogin_logical_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="receives_inactivity_reminder",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[("inactivity_7day", "7-day inactivity")], max_length=50
                    ),
                ),
                ("triggered_by_activity_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "reminder_type", "triggered_by_activity_at"),
                        name="unique_reminder_per_activity_period",
                    )
                ],
            },
        ),
    ]
