# Generated by Django 5.0.14 on 2025-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xp_next_level',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
