# Generated by Django 5.2.8 on 2025-12-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_alter_profile_xp_next_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="onboarding_step",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Not started"),
                    (1, "Step 1: Profile creation"),
                    (2, "Completed"),
                ],
                default=0,
            ),
        ),
    ]
