# Generated by Django 5.2.9 on 2026-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_alter_profile_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
