# Generated by Django 5.2.9 on 2026-01-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_profile_onboarding_completed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Player",
        ),
    ]
