# Generated by Django 5.2.9 on 2026-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_rename_profile_to_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="buffs",
        ),
        migrations.AlterField(
            model_name="player",
            name="onboarding_step",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Not started"),
                    (1, "Step 1: Player creation"),
                    (2, "Completed"),
                ],
                default=0,
            ),
        ),
    ]
