# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  migrate:
    build:
      context: .
      target: celery
    command: ["python", "manage.py", "migrate", "--noinput"]
    environment:
      - DJANGO_SETTINGS_MODULE=progress_rpg.settings.dev
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "progress_rpg.asgi:application"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - DOCKER="true"
    env_file:
     - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  db:
    image: postgis/postgis:16-3.4
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - DB_HOST=db
      - POSTGRES_USER=progress
      - POSTGRES_PASSWORD=progress
      - POSTGRES_DB=progress
      - DB_PORT=5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "progress"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: .
      target: celery
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=progress_rpg.settings.dev

  celery-beat:
    build:
      context: .
      target: celery-beat
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=progress_rpg.settings.dev

volumes:
  db-data:
