# Generated by Django 5.2.16 on 2026-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_gamesettings_waitlist_signup_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="xp_mastery_multiplier_cap",
            field=models.DecimalField(decimal_places=2, default="3.00", max_digits=5),
        ),
        migrations.AddField(
            model_name="gamesettings",
            name="xp_mastery_scale",
            field=models.DecimalField(
                decimal_places=2,
                default="1000.00",
                help_text="Skill XP needed for the Activity Points mastery multiplier to grow by +1.0x (see progression.points.xp_mastery_multiplier).",
                max_digits=10,
            ),
        ),
    ]
