# Generated by Django 5.2.16 on 2026-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_gamesettings_xp_mastery_multiplier_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="activity_compaction_cutoff_days",
            field=models.IntegerField(
                default=90,
                help_text="Completed CharacterActivity rows older than this are rolled into CharacterActivityArchive monthly summaries and deleted (see progression.tasks.compact_character_activities).",
            ),
        ),
    ]
