# Generated by Django 5.2.16 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_featureflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="daily_goals_completion_bonus_ap",
            field=models.IntegerField(
                default=50,
                help_text="Lump-sum AP awarded once per day when a player clears all three daily goals (see progression.daily_goals).",
            ),
        ),
    ]
