# Generated by Django 5.2.17 on 2026-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_gamesettings_daily_goals_completion_bonus_ap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=models.TextField(
                help_text="Supports Markdown (bold, links, lists, etc.)."
            ),
        ),
    ]
