# Generated by Django 5.2.17 on 2026-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_announcement_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="inactivity_reminders_enabled_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
