# Generated by Django 5.2.17 on 2026-08-23 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_gamesettings_inactivity_reminders_enabled_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="progressive_unlocks_enabled_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
