# Generated by Django 5.2.16 on 2026-08-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0003_alter_goodsstock_good_type"),
        ("locations", "0010_building_open_time_override_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("milling", "Milling"),
                            ("baking", "Baking"),
                            ("farming", "Farming"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="locations.building",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building", "activity"),
                        name="uniq_capability_per_building",
                    )
                ],
            },
        ),
    ]
