# Generated by Django 5.2.9 on 2026-01-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0037_remove_player_buffs_alter_player_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users_today', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('total_sessions_today', models.PositiveIntegerField(default=0)),
                ('total_activities_today', models.PositiveIntegerField(default=0)),
                ('total_minutes_today', models.PositiveIntegerField(default=0)),
                ('week_over_week_retention', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Global Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyEngagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('had_activity', models.BooleanField(default=False)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('activities_count', models.PositiveIntegerField(default=0)),
                ('minutes_active', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='users.player')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='metrics_dai_date_36c467_idx'), models.Index(fields=['player', 'date'], name='metrics_dai_player__af3197_idx')],
                'unique_together': {('player', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('active_days_count', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('activities_logged', models.PositiveIntegerField(default=0)),
                ('total_active_minutes', models.PositiveIntegerField(default=0)),
                ('retained_from_previous_week', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_metrics', to='users.player')),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['week_start'], name='metrics_use_week_st_2126ba_idx'), models.Index(fields=['player', 'week_start'], name='metrics_use_player__f62f05_idx')],
                'unique_together': {('player', 'week_start')},
            },
        ),
    ]
