# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metrics", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyengagementsnapshot",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_snapshots",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="userengagementmetrics",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_metrics",
                to="users.player",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyengagementsnapshot",
            index=models.Index(fields=["date"], name="metrics_dai_date_36c467_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyengagementsnapshot",
            index=models.Index(
                fields=["player", "date"], name="metrics_dai_player__af3197_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyengagementsnapshot",
            unique_together={("player", "date")},
        ),
        migrations.AddIndex(
            model_name="userengagementmetrics",
            index=models.Index(
                fields=["week_start"], name="metrics_use_week_st_2126ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userengagementmetrics",
            index=models.Index(
                fields=["player", "week_start"], name="metrics_use_player__f62f05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userengagementmetrics",
            unique_together={("player", "week_start")},
        ),
    ]
