# Generated by Django 5.2.9 on 2026-05-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("no", "No users"),
                            ("all", "All users"),
                            ("premium", "Premium users"),
                        ],
                        default="no",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
    ]
