# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0003_initial"),
        ("progression", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="characteractivity",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_activities",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_quests",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="characterskill",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.characterskill",
            ),
        ),
        migrations.AddField(
            model_name="playeractivity",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skills",
                to="progression.category",
            ),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="playeractivity",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.playerskill",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="playeractivity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.project",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="characterskill",
            name="roles",
            field=models.ManyToManyField(related_name="skills", to="progression.role"),
        ),
        migrations.AddField(
            model_name="task",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="progression.project",
            ),
        ),
        migrations.AddField(
            model_name="playeractivity",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.task",
            ),
        ),
        migrations.AddConstraint(
            model_name="playeractivity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("task__isnull", True), ("project__isnull", True), _connector="OR"
                ),
                name="activity_task_or_project_not_both",
            ),
        ),
    ]
