# Generated by Django 4.2.22 on 2025-08-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0002_move_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="xp_rate",
        ),
        migrations.AddField(
            model_name="activity",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
