# Generated by Django 5.2.9 on 2026-01-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0006_alter_playercharacterlink_character_and_more"),
        ("progression", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteractivity",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="character.character",
            ),
        ),
    ]
