# Generated by Django 5.2.13 on 2026-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0003_alter_characteractivity_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeractivity",
            name="group_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
