# Generated by Django 4.2.22 on 2025-08-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0003_remove_activity_xp_rate_activity_is_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="is_completed",
            new_name="is_complete",
        ),
    ]
