# Generated by Django 5.2.16 on 2026-08-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0005_task_first_completed_at"),
        ("users", "0012_waitlist_nudge_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeractivity",
            name="origin",
            field=models.CharField(
                choices=[("timer", "Timer"), ("manual", "Manual")],
                default="timer",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OfflineActivityLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("logged_seconds", models.PositiveIntegerField(default=0)),
                ("xp_eligible_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_activity_ledgers",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "date"),
                        name="unique_offline_ledger_player_date",
                    )
                ],
            },
        ),
    ]
