# Generated by Django 4.2.22 on 2025-08-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0007_character_can_link"),
        ("progression", "0005_activity_is_private_characterquest"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterquest",
            name="intro_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="outro_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="selected_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="stages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="stagesFixed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="characterquest",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_quests",
                to="character.character",
            ),
        ),
    ]
