# Generated by Django 4.2.22 on 2025-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "progression",
            "0006_characterquest_intro_text_characterquest_outro_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="characterquest",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="activity",
            name="xp_gained",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterquest",
            name="xp_gained",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
