# Generated by Django 5.2.16 on 2026-08-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0006_task_due_at_parent"),
        ("progression", "0007_alter_note_task"),
    ]

    operations = []
