# Generated by Django 4.2.22 on 2025-08-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "progression",
            "0007_activity_description_characterquest_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterquest",
            old_name="selected_duration",
            new_name="quest_duration",
        ),
    ]
