# Generated by Django 5.2.8 on 2025-12-15 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0008_rename_selected_duration_characterquest_quest_duration"),
        ("users", "0033_alter_profile_xp_next_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterquest",
            old_name="stagesFixed",
            new_name="stages_fixed",
        ),
        migrations.RenameField(
            model_name="characterquest",
            old_name="quest_duration",
            new_name="target_duration",
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                ("time", models.PositiveIntegerField(default=0)),
                ("total_activities", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="progression.project",
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("time", models.PositiveIntegerField(default=0)),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=0)),
                ("total_activities", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="progression.skill",
            ),
        ),
    ]
