# Generated by Django 5.2.8 on 2025-12-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0009_rename_stagesfixed_characterquest_stages_fixed_and_more"),
        ("users", "0033_alter_profile_xp_next_level"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="PlayerSkill",
        ),
    ]
