# Generated by Django 5.2.16 on 2026-08-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0008_finalize_role_skill_taxonomy"),
        ("progression", "0009_merge_20260806_1433"),
    ]

    operations = []
