# Generated by Django 5.2.8 on 2025-12-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0008_alter_character_xp_next_level"),
        ("progression", "0010_rename_skill_playerskill"),
        ("users", "0033_alter_profile_xp_next_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerskill",
            old_name="time",
            new_name="total_time",
        ),
        migrations.RemoveField(
            model_name="playerskill",
            name="total_activities",
        ),
        migrations.AddField(
            model_name="playerskill",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="total_records",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_skills",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="xp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("total_time", models.PositiveIntegerField(default=0)),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("xp", models.IntegerField(blank=True, null=True)),
                ("level", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_skills",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="characterquest",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quests",
                to="progression.characterskill",
            ),
        ),
    ]
