# Generated by Django 5.2.8 on 2025-12-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0008_alter_character_xp_next_level"),
        ("progression", "0011_rename_time_playerskill_total_time_and_more"),
        ("users", "0033_alter_profile_xp_next_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterskill",
            name="total_records",
        ),
        migrations.RemoveField(
            model_name="characterskill",
            name="total_time",
        ),
        migrations.RemoveField(
            model_name="characterskill",
            name="xp",
        ),
        migrations.RemoveField(
            model_name="playerskill",
            name="total_records",
        ),
        migrations.RemoveField(
            model_name="playerskill",
            name="total_time",
        ),
        migrations.RemoveField(
            model_name="playerskill",
            name="xp",
        ),
        migrations.RemoveField(
            model_name="project",
            name="time",
        ),
        migrations.RemoveField(
            model_name="project",
            name="total_activities",
        ),
        migrations.AlterField(
            model_name="activity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.project",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.playerskill",
            ),
        ),
        migrations.AlterField(
            model_name="characterquest",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.characterskill",
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="character.character",
            ),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="users.player",
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="playerskill",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skills",
                to="progression.category",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="characterskill",
            name="roles",
            field=models.ManyToManyField(related_name="skills", to="progression.role"),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="users.player",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="progression.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="progression.task",
            ),
        ),
    ]
