# Generated by Django 5.2.8 on 2025-12-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0012_remove_characterskill_total_records_and_more"),
        ("users", "0033_alter_profile_xp_next_level"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("task__isnull", True), ("project__isnull", True), _connector="OR"
                ),
                name="activity_task_or_project_not_both",
            ),
        ),
    ]
