# Generated by Django 5.2.8 on 2025-12-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0013_activity_activity_task_or_project_not_both"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
