# Generated by Django 5.2.8 on 2025-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0014_alter_project_description_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
