# Generated by Django 5.2.9 on 2026-01-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0008_alter_character_xp_next_level"),
        ("gameplay", "0103_rename_stagesfixed_quest_stages_fixed"),
        ("progression", "0015_project_completed_at_project_is_complete_and_more"),
        ("users", "0034_alter_profile_onboarding_step"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Activity",
            new_name="PlayerActivity",
        ),
        migrations.CreateModel(
            name="CharacterActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("xp_gained", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("day", "Daytime"), ("rest", "Resting")], max_length=50
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_activities",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
