# Generated by Django 5.2.9 on 2026-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0016_rename_activity_playeractivity_characteractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteractivity",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="characterquest",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="playeractivity",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
