# Generated by Django 5.2.9 on 2026-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0017_alter_characteractivity_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteractivity",
            name="scheduled_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteractivity",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteractivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("future", "Future"),
                    ("current", "Current"),
                    ("past", "Past"),
                ],
                default="future",
                max_length=20,
            ),
        ),
    ]
