# Generated by Django 5.2.9 on 2026-01-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0018_characteractivity_scheduled_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characteractivity",
            name="status",
        ),
    ]
