# Generated by Django 5.2.9 on 2026-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0019_remove_characteractivity_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteractivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("sleep", "Sleeping"),
                    ("morning", "Morning routine"),
                    ("work", "Working"),
                    ("meal", "Meal"),
                    ("leisure", "Leisure"),
                    ("wind_down", "Wind down"),
                    ("rest", "Resting"),
                    ("idle", "Idling"),
                ],
                max_length=50,
            ),
        ),
    ]
