# Generated by Django 5.2.16 on 2026-08-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0013_character_link_points_multiplier"),
        ("progression", "0019_remove_xp_gained"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterActivityArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of the archived month."),
                ),
                ("total_duration", models.PositiveIntegerField(default=0)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "activity_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_activity_archive",
                        to="progression.activitydefinition",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_archive",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "activity_definition", "month"),
                        name="unique_character_activity_archive_month",
                    )
                ],
            },
        ),
    ]
