# Generated by Django 5.2.16 on 2026-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0020_characteractivityarchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitydefinition",
            name="present_tense",
            field=models.CharField(
                blank=True,
                help_text="Narrative verb phrase for 'X is ___' sentences, e.g. 'delivering goods to neighbours' for the label 'Deliver goods to neighbours'. Falls back to a lowercased name when blank.",
                max_length=255,
            ),
        ),
    ]
