# Generated by Django 5.2.16 on 2026-08-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0021_activitydefinition_present_tense"),
        ("users", "0013_player_link_points_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="activity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="note",
                to="progression.activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("task__isnull", True), ("activity__isnull", True), _connector="OR"
                ),
                name="note_task_or_activity_not_both",
            ),
        ),
    ]
