# Generated by Django 5.2.16 on 2026-08-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0022_note_activity_note_note_task_or_activity_not_both"),
        ("users", "0013_player_link_points_multiplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyGoalAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("bonus_ap", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_goal_awards",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "date"),
                        name="unique_daily_goal_award_player_date",
                    )
                ],
            },
        ),
    ]
