# Generated by Django 5.2.17 on 2026-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0023_dailygoalaward"),
        ("users", "0014_customuser_day_start_time_userlogin_logical_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeractivity",
            name="logical_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="playeractivity",
            index=models.Index(
                fields=["player", "logical_date"], name="activity_player_logical_day"
            ),
        ),
    ]
