# Generated by Django 5.2.9 on 2026-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Behaviour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("friend", "Friend"),
                            ("rival", "Rival"),
                            ("mentor", "Mentor"),
                            ("enemy", "Enemy"),
                            ("ally", "Ally"),
                            ("romantic", "Romantic"),
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_exclusive", models.BooleanField(default=False)),
                ("strength", models.IntegerField(default=0)),
                ("history", models.JSONField(blank=True, default=dict)),
                ("biological", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterRelationshipMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerCharacterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_linked", models.DateField(auto_now_add=True)),
                ("date_unlinked", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("xp", models.PositiveIntegerField(default=0)),
                ("xp_next_level", models.PositiveIntegerField(default=100)),
                ("xp_modifier", models.FloatField(default=1)),
                ("level", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                (
                    "cause_of_death",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fertility", models.PositiveIntegerField(default=50)),
                ("last_childbirth_date", models.DateField(blank=True, null=True)),
                ("is_pregnant", models.BooleanField(default=False)),
                ("pregnancy_start_date", models.DateField(blank=True, null=True)),
                ("pregnancy_due_date", models.DateField(blank=True, null=True)),
                ("first_name", models.CharField(default="", max_length=50)),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("backstory", models.TextField(default="")),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=0)),
                ("reputation", models.IntegerField(default=0)),
                ("can_link", models.BooleanField(default=False)),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True, related_name="children", to="character.character"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
