# Generated by Django 4.2.17 on 2025-02-07 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0020_remove_profile_current_activity"),
        ("gameplay", "0066_remove_character_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("xp", models.PositiveIntegerField(default=0)),
                ("xp_next_level", models.PositiveIntegerField(default=0)),
                ("xp_modifier", models.FloatField(default=1)),
                ("level", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_quests", models.PositiveIntegerField(default=0)),
                ("first_name", models.CharField(default="", max_length=50)),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("backstory", models.TextField(default="")),
                ("gender", models.CharField(default="None", max_length=50)),
                ("is_pregnant", models.BooleanField(default=False)),
                ("pregnancy_start_date", models.DateField(blank=True, null=True)),
                ("pregnancy_due_date", models.DateTimeField(blank=True, null=True)),
                ("dob", models.DateField(default=django.utils.timezone.now)),
                ("dod", models.DateField(blank=True, null=True)),
                (
                    "cause_of_death",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("coins", models.PositiveIntegerField(default=0)),
                ("reputation", models.IntegerField(default=0)),
                ("is_npc", models.BooleanField(default=True)),
                (
                    "buffs",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="gameplay.buff"
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        related_name="children", to="character.character"
                    ),
                ),
                (
                    "quest_completions",
                    models.ManyToManyField(
                        related_name="completed_by",
                        through="gameplay.QuestCompletion",
                        to="gameplay.quest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerCharacterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_linked", models.DateField(auto_now_add=True)),
                ("date_unlinked", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_link",
                        to="character.character",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_link",
                        to="users.player",
                    ),
                ),
            ],
        ),
    ]
