# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="quest_completions",
            field=models.ManyToManyField(
                related_name="completed_by",
                through="gameplay.QuestCompletion",
                to="gameplay.quest",
            ),
        ),
        migrations.AddField(
            model_name="behaviour",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behaviour",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationshipmembership",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characterrelationshipmembership",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationshipmembership",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="characters",
            field=models.ManyToManyField(
                through="character.CharacterRelationshipMembership",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="playercharacterlink",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_link",
                to="character.character",
            ),
        ),
    ]
