# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playercharacterlink",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_link",
                to="users.player",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterrelationshipmembership",
            unique_together={("character", "relationship")},
        ),
        migrations.AddConstraint(
            model_name="playercharacterlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("player", "is_active"),
                name="one_active_link_per_player",
            ),
        ),
        migrations.AddConstraint(
            model_name="playercharacterlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("character", "is_active"),
                name="one_active_link_per_character",
            ),
        ),
    ]
