# Generated by Django 5.2.9 on 2026-01-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playercharacterlink",
            name="online_boost_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playercharacterlink",
            name="online_boost_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
