# Generated by Django 5.2.9 on 2026-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_playercharacterlink_online_boost_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playercharacterlink",
            name="online_boost_end_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
