# Generated by Django 5.2.9 on 2026-01-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_playercharacterlink_online_boost_end_task_id"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playercharacterlink",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="character.character",
            ),
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="users.player",
            ),
        ),
    ]
