# Generated by Django 5.2.9 on 2026-02-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_alter_playercharacterlink_linked_at_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playercharacterlink",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="character.character",
            ),
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="linked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="users.player",
            ),
        ),
    ]
