# Generated by Django 5.2.9 on 2026-01-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0006_alter_playercharacterlink_character_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playercharacterlink",
            name="online_boost_active",
        ),
        migrations.RemoveField(
            model_name="playercharacterlink",
            name="online_boost_end_task_id",
        ),
        migrations.RemoveField(
            model_name="playercharacterlink",
            name="online_boost_ends_at",
        ),
    ]
