# Generated by Django 5.0.14 on 2025-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_character_can_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='xp_next_level',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
