# Generated by Django 5.2.9 on 2026-01-30 17:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0007_remove_playercharacterlink_online_boost_active_and_more"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="locations.building",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="current_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movables_here",
                to="locations.node",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="is_moving",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0, srid=3857), srid=3857
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="movement_speed",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="character",
            name="population_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="locations.populationcentre",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="target_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movables_targeting",
                to="locations.node",
            ),
        ),
    ]
