# Generated by Django 5.2.9 on 2026-01-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0008_character_building_character_current_content_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="current_content_type",
        ),
        migrations.RemoveField(
            model_name="character",
            name="current_object_id",
        ),
    ]
