# Generated by Django 4.2.26 on 2025-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0008_alter_character_xp_next_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_moving",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="movement_speed",
            field=models.FloatField(default=1.0),
        ),
    ]
