# Generated by Django 5.2.9 on 2026-01-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_behaviour_behaviourday_scheduledbehaviour_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduledbehaviour",
            options={"ordering": ["start"]},
        ),
        migrations.RemoveField(
            model_name="behaviourday",
            name="character",
        ),
        migrations.RemoveField(
            model_name="scheduledbehaviour",
            name="character",
        ),
        migrations.AlterField(
            model_name="behaviour",
            name="current",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="character.scheduledbehaviour",
            ),
        ),
        migrations.AlterField(
            model_name="behaviourday",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="scheduledbehaviour",
            name="status",
            field=models.CharField(
                choices=[("future", "Future"), ("active", "Active"), ("past", "Past")],
                default="future",
                max_length=20,
            ),
        ),
    ]
