# Generated by Django 5.2.9 on 2026-02-08 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_rename_playercharacter_link_link_date_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playercharacterlink",
            name="linked_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="unlinked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
