# Generated by Django 5.2.8 on 2025-12-05 23:57

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_alter_character_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="position",
        ),
        migrations.AddField(
            model_name="character",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0, srid=3857), srid=3857
            ),
        ),
    ]
