# Generated by Django 5.2.9 on 2026-01-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_alter_scheduledbehaviour_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledbehaviour",
            name="day",
        ),
        migrations.RemoveField(
            model_name="scheduledbehaviour",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="behaviour",
            name="current",
        ),
        migrations.DeleteModel(
            name="BehaviourDay",
        ),
        migrations.DeleteModel(
            name="ScheduledBehaviour",
        ),
    ]
