# Generated by Django 5.2.8 on 2025-12-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0011_remove_character_position_character_location"),
        (
            "locations",
            "0009_remove_location_position_remove_building_position_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="locations.building",
            ),
        ),
    ]
