# Generated by Django 5.2.9 on 2026-01-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0011_remove_scheduledbehaviour_day_and_more"),
        ("users", "0035_profile_onboarding_completed"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="playercharacterlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("profile", "is_active"),
                name="one_active_link_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="playercharacterlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("character", "is_active"),
                name="one_active_link_per_character",
            ),
        ),
    ]
