# Generated by Django 5.2.8 on 2025-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0012_character_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_living",
            field=models.BooleanField(default=True),
        ),
    ]
