# Generated by Django 5.2.9 on 2026-01-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0012_playercharacterlink_one_active_link_per_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="is_npc",
        ),
    ]
