# Generated by Django 5.2.16 on 2026-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0012_alter_characterlocation_id_alter_characterneeds_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="link_points_multiplier",
            field=models.DecimalField(decimal_places=2, default="1.00", max_digits=5),
        ),
    ]
