# Generated by Django 5.2.8 on 2025-12-07 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0013_character_is_living"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="target_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=3857
            ),
        ),
    ]
