# Generated by Django 5.2.16 on 2026-08-06 21:43 (hand-edited: reordered ops
# so `variant` is populated from `biological` before `biological` is dropped)

from django.db import migrations, models


def backfill_variant_from_biological(apps, schema_editor):
    CharacterRelationship = apps.get_model("character", "CharacterRelationship")
    CharacterRelationship.objects.filter(biological=True).update(variant="biological")
    CharacterRelationship.objects.filter(biological=False).update(variant="adoptive")


def noop_reverse(apps, schema_editor):
    # variant -> biological isn't a clean inverse (variant has more values
    # than the old boolean did), so reversing this migration just leaves
    # `biological` at its field default rather than trying to guess.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0013_character_link_points_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterrelationship",
            name="variant",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.RunPython(
            backfill_variant_from_biological, reverse_code=noop_reverse
        ),
        migrations.RemoveField(
            model_name="characterrelationship",
            name="biological",
        ),
        migrations.AlterField(
            model_name="characterrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("friend", "Friend"),
                    ("rival", "Rival"),
                    ("mentor", "Mentor"),
                    ("enemy", "Enemy"),
                    ("ally", "Ally"),
                    ("romantic", "Romantic"),
                    ("spouse", "Spouse"),
                    ("parent_child", "Parent/Child"),
                    ("sibling", "Sibling"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="characterrelationshipmembership",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("participant", "Participant"),
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
