# Generated by Django 5.2.9 on 2026-01-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0014_rename_profile_fields_to_player"),
        ("users", "0037_remove_player_buffs_alter_player_onboarding_step"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playercharacterlink",
            name="one_active_link_per_profile",
        ),
        migrations.RemoveField(
            model_name="character",
            name="buffs",
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_link",
                to="character.character",
            ),
        ),
        migrations.AddConstraint(
            model_name="playercharacterlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("player", "is_active"),
                name="one_active_link_per_player",
            ),
        ),
    ]
