# Generated by Django 5.2.8 on 2025-12-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0015_character_target_content_type_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="current_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_movables",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="current_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
