# Generated by Django 5.2.16 on 2026-08-07 11:17

from django.db import migrations, models


def migrate_spouse_to_marriage(apps, schema_editor):
    CharacterRelationship = apps.get_model("character", "CharacterRelationship")
    CharacterRelationshipMembership = apps.get_model(
        "character", "CharacterRelationshipMembership"
    )

    relationship_ids = list(
        CharacterRelationship.objects.filter(relationship_type="spouse").values_list(
            "id", flat=True
        )
    )
    CharacterRelationship.objects.filter(id__in=relationship_ids).update(
        relationship_type="marriage"
    )
    CharacterRelationshipMembership.objects.filter(
        relationship_id__in=relationship_ids, role="participant"
    ).update(role="spouse")


def migrate_marriage_to_spouse(apps, schema_editor):
    CharacterRelationship = apps.get_model("character", "CharacterRelationship")
    CharacterRelationshipMembership = apps.get_model(
        "character", "CharacterRelationshipMembership"
    )

    relationship_ids = list(
        CharacterRelationship.objects.filter(relationship_type="marriage").values_list(
            "id", flat=True
        )
    )
    CharacterRelationshipMembership.objects.filter(
        relationship_id__in=relationship_ids, role="spouse"
    ).update(role="participant")
    CharacterRelationship.objects.filter(id__in=relationship_ids).update(
        relationship_type="spouse"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0015_migrate_parents_to_relationships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("friend", "Friend"),
                    ("rival", "Rival"),
                    ("mentor", "Mentor"),
                    ("enemy", "Enemy"),
                    ("ally", "Ally"),
                    ("romantic", "Romantic"),
                    ("marriage", "Marriage"),
                    ("parent_child", "Parent/Child"),
                    ("sibling", "Sibling"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="characterrelationshipmembership",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("participant", "Participant"),
                    ("spouse", "Spouse"),
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(
            migrate_spouse_to_marriage, reverse_code=migrate_marriage_to_spouse
        ),
    ]
