# Generated by Django 5.2.8 on 2025-12-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0016_character_current_content_type_and_more"),
        ("locations", "0014_remove_landarea_usage_landarea_size_subzone_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="population_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="locations.populationcentre",
            ),
        ),
    ]
