# Generated by Django 5.2.16 on 2026-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0016_rename_spouse_to_marriage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="quest_completions",
        ),
    ]
