# Generated by Django 5.2.16 on 2026-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0017_remove_character_quest_completions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="character",
            name="name",
        ),
    ]
