# Generated by Django 5.2.8 on 2025-12-13 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0017_character_population_centre"),
        (
            "locations",
            "0018_remove_path_is_bidirectional_path_population_centre_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="target_content_type",
        ),
        migrations.RemoveField(
            model_name="character",
            name="target_location",
        ),
        migrations.RemoveField(
            model_name="character",
            name="target_object_id",
        ),
        migrations.AddField(
            model_name="character",
            name="current_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movables_here",
                to="locations.node",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="target_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movables_targeting",
                to="locations.node",
            ),
        ),
    ]
