# Generated by Django 5.2.16 on 2026-08-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0019_rename_first_name_to_given_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="building",
        ),
    ]
