# Generated by Django 5.2.17 on 2026-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0020_remove_character_building"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="can_link",
        ),
        migrations.AddField(
            model_name="character",
            name="is_reserved",
            field=models.BooleanField(
                default=False,
                help_text="Manually held back from linking (e.g. reserved for a future storyline), independent of age or link status.",
                verbose_name="Reserved",
            ),
        ),
    ]
