# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.utils.timezone
import gameplay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityTimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("elapsed_time", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("waiting", "Waiting"),
                            ("completed", "Completed"),
                            ("empty", "Empty"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("intro_text", models.TextField(blank=True, max_length=2000)),
                ("outro_text", models.TextField(blank=True, max_length=2000)),
                (
                    "duration_choices",
                    models.JSONField(
                        default=gameplay.models.Quest.default_duration_choices
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("stages", models.JSONField(default=list)),
                (
                    "stages_fixed",
                    models.BooleanField(
                        default=False,
                        help_text="True if stages must appear in a certain order.",
                    ),
                ),
                ("category", models.CharField(default="NONE", max_length=20)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_task_support", models.BooleanField(default=False)),
                ("levelMin", models.PositiveIntegerField(default=0)),
                ("levelMax", models.PositiveIntegerField(default=0)),
                ("canRepeat", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("NONE", "No limit"),
                            ("DAY", "Daily"),
                            ("WEEK", "Weekly"),
                            ("MONTH", "Monthly"),
                        ],
                        default="NONE",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times_completed", models.PositiveIntegerField(default=1)),
                (
                    "last_completed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times_required", models.PositiveIntegerField(default=1)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dynamic_rewards",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("xp_rate", models.PositiveIntegerField(default=1)),
                ("coin_reward", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestTimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("elapsed_time", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("waiting", "Waiting"),
                            ("completed", "Completed"),
                            ("empty", "Empty"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                ("duration", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServerMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        help_text="WebSocket group to send this message to.",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("server_message", "Server Message"),
                            ("action", "Action"),
                            ("response", "Response"),
                            ("error", "Error"),
                            ("notification", "Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("data", models.JSONField(blank=True, null=True)),
                ("message", models.TextField(blank=True, max_length=2000, null=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_draft", models.BooleanField(default=True)),
            ],
        ),
    ]
