# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gameplay", "0001_initial"),
        ("progression", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytimer",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_timer",
                to="progression.playeractivity",
            ),
        ),
    ]
