# Generated by Django 5.2.9 on 2026-01-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0003_initial"),
        ("gameplay", "0002_initial"),
        ("progression", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytimer",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_timer",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="questcompletion",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="questcompletion",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_completions",
                to="gameplay.quest",
            ),
        ),
        migrations.AddField(
            model_name="questrequirement",
            name="prerequisite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for",
                to="gameplay.quest",
            ),
        ),
        migrations.AddField(
            model_name="questrequirement",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_requirements",
                to="gameplay.quest",
            ),
        ),
        migrations.AddField(
            model_name="questresults",
            name="quest",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="gameplay.quest",
            ),
        ),
        migrations.AddField(
            model_name="questtimer",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_timer",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="questtimer",
            name="quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quest_timer",
                to="progression.characterquest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questcompletion",
            unique_together={("character", "quest")},
        ),
        migrations.AlterUniqueTogether(
            name="questrequirement",
            unique_together={("quest", "prerequisite")},
        ),
    ]
