# Generated by Django 5.2.9 on 2026-02-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0006_alter_playercharacterlink_character_and_more"),
        ("gameplay", "0003_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XpModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("PLAYER", "Player"),
                            ("CHARACTER", "Character"),
                            ("LINK", "Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                (
                    "multiplier",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional Celery task ID for scheduled end task.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_mods",
                        to="character.character",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_mods",
                        to="character.playercharacterlink",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_mods",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "is_active", "starts_at", "ends_at"],
                        name="gameplay_xp_key_e9b4fc_idx",
                    )
                ],
            },
        ),
    ]
