# Generated by Django 5.2.9 on 2026-03-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0004_xpmodifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xpmodifier",
            name="link",
        ),
        migrations.AlterField(
            model_name="xpmodifier",
            name="scope",
            field=models.CharField(
                choices=[("PLAYER", "Player"), ("CHARACTER", "Character")],
                max_length=20,
            ),
        ),
    ]
