# Generated by Django 5.2.9 on 2026-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0004_xpmodifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="xpmodifier",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Optional Celery task ID for scheduled end task.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="xpmodifier",
            name="scope",
            field=models.CharField(
                choices=[
                    ("PLAYER", "Player"),
                    ("CHARACTER", "Character"),
                    ("LINK", "Link"),
                ],
                max_length=20,
            ),
        ),
    ]
