# Generated by Django 5.2.9 on 2026-01-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0007_remove_playercharacterlink_online_boost_active_and_more"),
        ("gameplay", "0005_xpmodifier_task_id_alter_xpmodifier_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="xpmodifier",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xp_mods",
                to="character.playercharacterlink",
            ),
        ),
    ]
