# Generated by Django 5.2.16 on 2026-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0017_remove_character_quest_completions"),
        ("gameplay", "0008_alter_questtimer_quest"),
    ]

    operations = [
        # AlterUniqueTogether must run before the RemoveField ops below -
        # questcompletion/questrequirement's unique_together reference the
        # "quest"/"character"/"prerequisite" columns being removed, and
        # dropping a column still listed in a unique_together constraint
        # fails (see FieldDoesNotExist during database_forwards).
        migrations.AlterUniqueTogether(
            name="questcompletion",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="questrequirement",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="questrequirement",
            name="quest",
        ),
        migrations.RemoveField(
            model_name="questcompletion",
            name="quest",
        ),
        migrations.RemoveField(
            model_name="questrequirement",
            name="prerequisite",
        ),
        migrations.RemoveField(
            model_name="questtimer",
            name="quest",
        ),
        migrations.RemoveField(
            model_name="questcompletion",
            name="character",
        ),
        migrations.RemoveField(
            model_name="questtimer",
            name="character",
        ),
        migrations.DeleteModel(
            name="QuestResults",
        ),
        migrations.DeleteModel(
            name="QuestRequirement",
        ),
        migrations.DeleteModel(
            name="Quest",
        ),
        migrations.DeleteModel(
            name="QuestCompletion",
        ),
        migrations.DeleteModel(
            name="QuestTimer",
        ),
    ]
