# Generated by Django 5.2.17 on 2026-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0009_remove_questrequirement_quest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytimer",
            name="limit_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="activitytimer",
            name="limit_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
