# Generated by Django 4.2.17 on 2025-02-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0052_project_activity_skill_character_gender_and_more"),
        ("gameworld", "0001_initial"),
        ("users", "0019_rename_create_at_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gameworld.location",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="x_coordinate",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="y_coordinate",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="character",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="users.player",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="gameplay.project",
            ),
        ),
    ]
