# Generated by Django 4.2.17 on 2025-02-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_rename_create_at_customuser_created_at_and_more"),
        ("gameplay", "0059_alter_character_dod_alter_character_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="age",
        ),
        migrations.RemoveField(
            model_name="character",
            name="profile",
        ),
        migrations.AddField(
            model_name="character",
            name="cause_of_death",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="backstory",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="PlayerCharacterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_linked", models.DateField(auto_now_add=True)),
                ("date_unlinked", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_link",
                        to="gameplay.character",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_link",
                        to="users.player",
                    ),
                ),
            ],
        ),
    ]
