# Generated by Django 4.2.17 on 2025-02-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_rename_create_at_customuser_created_at_and_more"),
        ("gameplay", "0062_alter_character_is_npc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitytimer",
            name="is_running",
        ),
        migrations.RemoveField(
            model_name="character",
            name="current_quest",
        ),
        migrations.RemoveField(
            model_name="questtimer",
            name="is_running",
        ),
        migrations.AddField(
            model_name="activitytimer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("empty", "Empty"),
                ],
                default="empty",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="default_duration",
            field=models.IntegerField(
                choices=[
                    (5, "5 minutes"),
                    (10, "10 minutes"),
                    (15, "15 minutes"),
                    (20, "20 minutes"),
                    (25, "25 minutes"),
                    (30, "30 minutes"),
                ],
                default=5,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="xp_rate",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="questtimer",
            name="quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quest_timer",
                to="gameplay.quest",
            ),
        ),
        migrations.AddField(
            model_name="questtimer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("empty", "Empty"),
                ],
                default="empty",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitytimer",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_timer",
                to="gameplay.activity",
            ),
        ),
        migrations.AlterField(
            model_name="activitytimer",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_timer",
                to="users.player",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="quest",
            name="intro_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="quest",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="quest",
            name="outro_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="questresults",
            name="dynamic_rewards",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="questresults",
            name="xp_reward",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questtimer",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_timer",
                to="gameplay.character",
            ),
        ),
    ]
