# Generated by Django 4.2.17 on 2025-02-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_profile_current_activity"),
        ("character", "0001_initial"),
        ("gameplay", "0066_remove_character_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="quest_completions",
        ),
        migrations.AlterField(
            model_name="character",
            name="buffs",
            field=models.ManyToManyField(
                blank=True, related_name="charactersWIP", to="gameplay.buff"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="parents",
            field=models.ManyToManyField(
                related_name="childrenWIP", to="gameplay.character"
            ),
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_linkWIP",
                to="gameplay.character",
            ),
        ),
        migrations.AlterField(
            model_name="playercharacterlink",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_linkWIP",
                to="users.player",
            ),
        ),
        migrations.AlterField(
            model_name="questcompletion",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AlterField(
            model_name="questtimer",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_timerWIP",
                to="character.character",
            ),
        ),
    ]
