# Generated by Django 4.2.17 on 2025-03-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_customuser_delete_at_customuser_pending_delete"),
        ("gameplay", "0081_pendingnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("action", "Action"),
                            ("response", "Response"),
                            ("error", "Error"),
                            ("notification", "Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                ("message", models.TextField(blank=True, max_length=2000, null=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_notifications",
                        to="users.player",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PendingNotification",
        ),
    ]
