# Generated by Django 4.2.22 on 2025-08-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0096_activity_xp_gained"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="project",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="skill",
        ),
    ]
