# Generated by Django 4.2.22 on 2025-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0096_activity_xp_gained"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="is_task_support",
            field=models.BooleanField(default=False),
        ),
    ]
