# Generated by Django 4.2.26 on 2025-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0096_activity_xp_gained"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="stagesFixed",
            field=models.BooleanField(
                default=False,
                help_text="True if stages must appear in a certain order.",
            ),
        ),
    ]
