# Generated by Django 4.2.22 on 2025-08-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0097_remove_activity_profile_remove_activity_project_and_more"),
        ("progression", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytimer",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_timer",
                to="progression.activity",
            ),
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
