# Generated by Django 5.2.8 on 2025-12-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0097_alter_quest_stagesfixed"),
        ("gameplay", "0097_quest_is_task_support"),
    ]

    operations = []
