# Generated by Django 4.2.25 on 2025-11-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0008_rename_selected_duration_characterquest_quest_duration"),
        ("gameplay", "0098_alter_activitytimer_activity_delete_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="stagesFixed",
            field=models.BooleanField(
                default=False,
                help_text="True if stages must appear in a certain order.",
            ),
        ),
        migrations.AlterField(
            model_name="questtimer",
            name="quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quest_timer",
                to="progression.characterquest",
            ),
        ),
    ]
