# Generated by Django 5.2.8 on 2025-12-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0098_merge_20251214_1617"),
        ("gameplay", "0099_alter_quest_stagesfixed_alter_questtimer_quest"),
    ]

    operations = []
