# Generated by Django 5.2.8 on 2025-12-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0100_merge_20251215_0117"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="profile",
        ),
    ]
