# Generated by Django 5.2.8 on 2025-12-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0101_remove_project_profile_remove_skill_profile"),
        ("progression", "0009_rename_stagesfixed_characterquest_stages_fixed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
