# Generated by Django 5.2.8 on 2025-12-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0102_delete_project_delete_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quest",
            old_name="stagesFixed",
            new_name="stages_fixed",
        ),
    ]
