# Generated by Django 5.2.9 on 2026-01-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0015_remove_playercharacterlink_one_active_link_per_profile_and_more",
        ),
        ("gameplay", "0104_rename_profile_fields_to_player"),
        ("users", "0037_remove_player_buffs_alter_player_onboarding_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questresults",
            name="buffs",
        ),
        migrations.DeleteModel(
            name="AppliedBuff",
        ),
        migrations.DeleteModel(
            name="Buff",
        ),
    ]
