VILLAGE_NAMES = [
    "Bramblewick",
    "Ashenford",
    "Willowmere",
    "Thornhollow",
    "Eldergate",
    "Stonebrook",
    "Ravenshade",
    "Oakenshire",
    "Driftmoor",
    "Coldwater Reach",
    "Millhaven",
    "Blackthorn Vale",
    "Foxglove Crossing",
    "Hallowmere",
    "Ironholt",
    "Mossbury",
    "Windmere",
    "Greycliff",
    "Barrowden",
    "Kingsmere",
]
