# Generated by Django 5.2.9 on 2026-01-30 17:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0007_remove_playercharacterlink_online_boost_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("granary", "Granary"),
                            ("inn", "Inn"),
                            ("mill", "Mill"),
                            ("bakery", "Bakery"),
                            ("communal", "Communal"),
                        ],
                        default="residential",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0, srid=3857),
                        help_text="Centre location",
                        srid=3857,
                    ),
                ),
                (
                    "footprint",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PopulationCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0, srid=3857),
                        srid=3857,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InteriorSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                ("area", models.FloatField()),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("living", "Living"),
                            ("sleeping", "Sleeping"),
                            ("hygiene", "Hygiene"),
                            ("kitchen", "Kitchen"),
                            ("storage", "Storage"),
                            ("workshop", "Workshop"),
                            ("animals", "Animals"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interiorspaces",
                        to="locations.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=3857)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("centre", "Centre"),
                            ("outside", "Outside"),
                            ("building", "Building"),
                            ("building_entrance", "Building Entrance"),
                            ("interior", "Interior"),
                            ("poi", "Point of Interest"),
                        ],
                        default="outside",
                        max_length=20,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="locations.building",
                    ),
                ),
                (
                    "interior_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="locations.interiorspace",
                    ),
                ),
                (
                    "population_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="locations.populationcentre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                ("size", models.FloatField(help_text="Size of land area in hectares")),
                (
                    "population_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="land_areas",
                        to="locations.populationcentre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="population_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="locations.populationcentre",
            ),
        ),
        migrations.CreateModel(
            name="Subzone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                ("size", models.FloatField(help_text="Size of subzone in hectares")),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("crops", "Crop Growing"),
                            ("grazing", "Grazing Land"),
                            ("foraging", "Foraging"),
                            ("woodland", "Woodland"),
                            ("orchard", "Orchard"),
                            ("other", "Other"),
                        ],
                        default="crops",
                        max_length=50,
                    ),
                ),
                (
                    "land_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subzones",
                        to="locations.landarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_nodes", models.JSONField(blank=True, null=True)),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="character.character",
                    ),
                ),
                (
                    "destination_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys_ending",
                        to="locations.node",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys_started",
                        to="locations.node",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character", "status"], name="journey_char_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("character",),
                        name="uniq_active_journey_per_character",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.FloatField(blank=True, null=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths_from",
                        to="locations.node",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths_to",
                        to="locations.node",
                    ),
                ),
                (
                    "population_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="locations.populationcentre",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["population_centre"],
                        name="locations_p_populat_aa60f8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_node", "to_node"), name="uniq_path_directed"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["population_centre"], name="node_pc_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["kind"], name="node_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("building__isnull", False)),
                fields=("building", "kind"),
                name="uniq_node_building_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building__isnull", True), ("interior_space__isnull", True)
                    ),
                    ("population_centre__isnull", True),
                    _connector="OR",
                ),
                name="node_population_centre_xor_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("building__isnull", True),
                    ("interior_space__isnull", True),
                    _connector="OR",
                ),
                name="node_building_or_interior",
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["population_centre"], name="locations_b_populat_d02a0f_idx"
            ),
        ),
    ]
