# Generated by Django 5.2.9 on 2026-02-12 12:18

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        CreateExtension("postgis"),
    ]
