# Generated by Django 5.2.9 on 2026-01-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="kind",
            field=models.CharField(
                choices=[
                    ("centre", "Centre"),
                    ("outside", "Outside"),
                    ("building", "Building"),
                    ("building_entrance", "Building Entrance"),
                    ("interior", "Interior"),
                    ("poi", "Point of Interest"),
                ],
                default="outside",
                max_length=20,
            ),
        ),
    ]
