# Generated by Django 5.2.9 on 2026-01-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_node_kind"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="path",
            constraint=models.UniqueConstraint(
                fields=("from_node", "to_node"), name="uniq_path_directed"
            ),
        ),
    ]
