# Generated by Django 4.2.26 on 2025-11-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0002_remove_animalpen_farm_space_remove_building_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="position",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="locations.position",
            ),
            preserve_default=False,
        ),
    ]
