# Generated by Django 5.2.9 on 2026-01-29 23:18

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_path_uniq_path_directed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0, srid=3857),
                help_text="Centre location",
                srid=3857,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["population_centre"], name="locations_b_populat_d02a0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["population_centre"], name="locations_n_populat_ab7509_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["kind"], name="locations_n_kind_57b09c_idx"),
        ),
        migrations.AddIndex(
            model_name="path",
            index=models.Index(
                fields=["population_centre"], name="locations_p_populat_aa60f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("building__isnull", False)),
                fields=("building",),
                name="uniq_node_building",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building__isnull", True), ("interior_space__isnull", True)
                    ),
                    ("population_centre__isnull", True),
                    _connector="OR",
                ),
                name="node_population_centre_xor_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("building__isnull", True),
                    ("interior_space__isnull", True),
                    _connector="OR",
                ),
                name="node_building_or_interior",
            ),
        ),
    ]
