# Generated by Django 5.2.9 on 2026-01-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0008_character_building_character_current_content_type_and_more",
        ),
        ("locations", "0004_alter_building_location_alter_journey_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="character.character",
            ),
        ),
    ]
