# Generated by Django 4.2.26 on 2025-11-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_location_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="position",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.position",
            ),
        ),
    ]
