# Generated by Django 5.2.9 on 2026-01-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_journey_character"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="node",
            name="uniq_node_building",
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("building__isnull", False)),
                fields=("building", "kind"),
                name="uniq_node_building_kind",
            ),
        ),
    ]
