# Generated by Django 4.2.26 on 2025-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "buildings",
                    models.ManyToManyField(blank=True, to="locations.building"),
                ),
            ],
        ),
    ]
