# Generated by Django 5.2.9 on 2026-01-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_remove_node_uniq_node_building_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="node",
            new_name="node_pc_idx",
            old_name="locations_n_populat_ab7509_idx",
        ),
        migrations.RenameIndex(
            model_name="node",
            new_name="node_kind_idx",
            old_name="locations_n_kind_57b09c_idx",
        ),
    ]
