# Generated by Django 5.2.9 on 2026-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_remove_character_current_content_type_and_more"),
        (
            "locations",
            "0007_rename_locations_n_populat_ab7509_idx_node_pc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("character",),
                name="uniq_active_journey_per_character",
            ),
        ),
    ]
