# Generated by Django 5.2.8 on 2025-12-05 23:57

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0011_remove_character_position_character_location"),
        ("gameworld", "0013_remove_weatherevent_location"),
        ("locations", "0008_populationcentre_building_population_centre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="position",
        ),
        migrations.RemoveField(
            model_name="building",
            name="position",
        ),
        migrations.RemoveField(
            model_name="populationcentre",
            name="position",
        ),
        migrations.RemoveField(
            model_name="building",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="building",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="building",
            name="footprint",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=3857
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0, srid=3857),
                help_text="Entrance location",
                srid=3857,
            ),
        ),
        migrations.AddField(
            model_name="populationcentre",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=3857
            ),
        ),
        migrations.AddField(
            model_name="populationcentre",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0, srid=3857), srid=3857
            ),
        ),
        migrations.DeleteModel(
            name="Area",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
