# Generated by Django 5.2.9 on 2026-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_remove_character_current_content_type_and_more"),
        ("locations", "0008_journey_uniq_active_journey_per_character"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["character", "status"], name="journey_char_status_idx"
            ),
        ),
    ]
