# Generated by Django 5.2.16 on 2026-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_merge_0007_alter_building_name_0007_road"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("granary", "Granary"),
                    ("inn", "Inn"),
                    ("mill", "Mill"),
                    ("bakery", "Bakery"),
                    ("hall", "Hall"),
                    ("market", "Market"),
                    ("communal", "Communal"),
                    ("field_shelter", "Field Shelter"),
                ],
                default="residential",
                max_length=50,
            ),
        ),
    ]
