# Generated by Django 5.2.8 on 2025-12-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_location_position_remove_building_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('use', models.CharField(choices=[('living', 'Living'), ('sleeping', 'Sleeping'), ('cooking', 'Cooking'), ('storage', 'Storage'), ('workshop', 'Workshop'), ('animals', 'Animals'), ('communal', 'Communal'), ('other', 'Other')], max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interiorspaces', to='locations.building')),
            ],
        ),
    ]
