# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_alter_building_building_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="open_time_override",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="close_time_override",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
