# Generated by Django 5.2.9 on 2026-01-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_journey_journey_char_status_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="locations.building",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="interior_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="locations.interiorspace",
            ),
        ),
    ]
