# Generated by Django 5.2.17 on 2026-08-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_building_open_time_override_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subzone",
            name="usage",
            field=models.CharField(
                choices=[
                    ("crops", "Crop Growing"),
                    ("grazing", "Grazing Land"),
                    ("foraging", "Foraging"),
                    ("woodland", "Woodland"),
                    ("orchard", "Orchard"),
                    ("square", "Square"),
                    ("other", "Other"),
                ],
                default="crops",
                max_length=50,
            ),
        ),
    ]
