# Generated by Django 5.2.8 on 2025-12-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_interiorspace"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interiorspace",
            old_name="use",
            new_name="usage",
        ),
    ]
