# Generated by Django 5.2.8 on 2025-12-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0011_rename_use_interiorspace_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interiorspace",
            name="usage",
            field=models.CharField(
                choices=[
                    ("living", "Living"),
                    ("sleeping", "Sleeping"),
                    ("hygiene", "Hygiene"),
                    ("cooking", "Cooking"),
                    ("storage", "Storage"),
                    ("workshop", "Workshop"),
                    ("animals", "Animals"),
                    ("communal", "Communal"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
