# Generated by Django 5.2.8 on 2025-12-10 00:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0012_alter_interiorspace_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="interiorspace",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=3857
            ),
        ),
        migrations.CreateModel(
            name="LandArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("crops", "Crop Growing"),
                            ("grazing", "Grazing Land"),
                            ("foraging", "Foraging"),
                            ("woodland", "Woodland"),
                            ("clay", "Clay / Resource"),
                            ("communal", "General Communal Ground"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "population_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="land_areas",
                        to="locations.populationcentre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subzone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "land_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subareas",
                        to="locations.landarea",
                    ),
                ),
            ],
        ),
    ]
