# Generated by Django 5.2.8 on 2025-12-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0013_interiorspace_location_landarea_subzone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landarea",
            name="usage",
        ),
        migrations.AddField(
            model_name="landarea",
            name="size",
            field=models.FloatField(
                default=1, help_text="Size of land area in hectares"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subzone",
            name="size",
            field=models.FloatField(default=1, help_text="Size of subzone in hectares"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subzone",
            name="usage",
            field=models.CharField(
                choices=[
                    ("crops", "Crop Growing"),
                    ("grazing", "Grazing Land"),
                    ("foraging", "Foraging"),
                    ("woodland", "Woodland"),
                    ("orchard", "Orchard"),
                    ("other", "Other"),
                ],
                default="crops",
                max_length=50,
            ),
        ),
    ]
