# Generated by Django 5.2.8 on 2025-12-10 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0014_remove_landarea_usage_landarea_size_subzone_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("granary", "Granary"),
                    ("inn", "Inn"),
                    ("mill", "Mill"),
                    ("bakery", "Bakery"),
                    ("communal", "Communal"),
                ],
                default="residential",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interiorspace",
            name="usage",
            field=models.CharField(
                choices=[
                    ("living", "Living"),
                    ("sleeping", "Sleeping"),
                    ("hygiene", "Hygiene"),
                    ("kitchen", "Kitchen"),
                    ("storage", "Storage"),
                    ("workshop", "Workshop"),
                    ("animals", "Animals"),
                    ("meeting", "Meeting"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subzone",
            name="land_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subzones",
                to="locations.landarea",
            ),
        ),
    ]
