# Generated by Django 5.2.8 on 2025-12-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0016_node_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.building",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="population_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.populationcentre",
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="is_bidirectional",
            field=models.BooleanField(default=True),
        ),
    ]
