# Generated by Django 5.2.8 on 2025-12-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0017_character_population_centre"),
        ("locations", "0017_node_building_node_population_centre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="path",
            name="is_bidirectional",
        ),
        migrations.AddField(
            model_name="path",
            name="population_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="locations.populationcentre",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node",
                to="locations.building",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="population_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="locations.populationcentre",
            ),
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_nodes", models.JSONField(blank=True, null=True)),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="ongoing", max_length=20)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
                (
                    "destination_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys_ending",
                        to="locations.node",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys_started",
                        to="locations.node",
                    ),
                ),
            ],
        ),
    ]
