# Generated by Django 5.2.8 on 2025-12-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_remove_path_is_bidirectional_path_population_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='interior_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='locations.interiorspace'),
        ),
    ]
