# Generated by Django 5.2.8 on 2025-12-24 00:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0019_node_interior_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
