"""
Django settings for progress_rpg project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys
import dj_database_url
from decouple import Config, RepositoryEnv, config
import os
from dotenv import load_dotenv
import logging, ssl, sentry_sdk

from .utils import is_vite_running

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path)

CURRENT_ENV = os.getenv("CURRENT_ENV", "local")

DEBUG = os.getenv("DEBUG", "True") == "True"
os.environ.setdefault("DEBUG", "True")


os.environ.setdefault(
    "DJANGO_SETTINGS_MODULE",
    os.getenv("DJANGO_SETTINGS_MODULE", "progress_rpg.settings.dev"),
)

# see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=CURRENT_ENV,
        send_default_pii=CURRENT_ENV != "production",
        traces_sample_rate=1.0,
    )

APP_VERSION = "0.6.0-alpha"

TOKEN_MODEL = None

# Application definition
# Test for Ruth

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "rest_framework",
    "django_filters",
    "dj_rest_auth",
    "rest_framework_simplejwt",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    "rest_framework.authtoken",
    "django.contrib.admin",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_celery_beat",
    "django_cf_turnstile",
    "django_extensions",
    "drf_spectacular",
    "channels",
    "django_vite",
    "sendgrid",
    "character",
    "gameplay",
    "gameworld",
    # "events",
    "locations",
    "payments",
    "progression",
    "server_management",
    "users",
    "metrics",
    "django_ratelimit",
    "decouple",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "progress_rpg.middleware.logging_context.RequestLoggingMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "progress_rpg.middleware.timezone.UserTimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    #'server_management.middleware.AsyncMaintenanceModeMiddleware',
    #'server_management.middleware.AsyncBlockBotMiddleware',
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "progress_rpg.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = 'progress_rpg.wsgi.application'
ASGI_APPLICATION = "progress_rpg.asgi.application"


REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "JSON_ENCODER_INDENT": 2,  # Pretty-print JSON with 2-space indentation
    "UNICODE_JSON": True,  # Don't escape Unicode characters
    "COMPACT_JSON": False,  # Add whitespace for readability
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        #'rest_framework.authentication.SessionAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "api.serializers.CustomRegisterSerializer",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Progress RPG API",
    "DESCRIPTION": "API documentation for Progress RPG, an ADHD-focused productivity game.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_USE_JWT = True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "users.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",  # fallback default
]


ACCOUNT_ADAPTER = "users.adapters.CustomAccountAdapter"
AUTH_USER_MODEL = "users.CustomUser"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_HTML_TEMPLATE = (
    "account/email/email_confirmation_message.html"
)
ACCOUNT_EMAIL_CONFIRMATION_TEMPLATE = "account/email/email_confirmation_message.txt"


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-gb"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Vite settings

django_vite_dev_mode = os.getenv("DJANGO_VITE_DEV_MODE")
if django_vite_dev_mode is None:
    DEV_MODE = is_vite_running()
else:
    DEV_MODE = django_vite_dev_mode.lower() in ("true", "1", "yes")

print("DEV_MODE =", DEV_MODE, file=sys.stderr)

DJANGO_VITE = {
    "default": {
        "dev_mode": DEV_MODE,
        "dev_server_port": 5173,
        "dev_server_host": "localhost",
        "static_url_prefix": "frontend/",
        "manifest_path": BASE_DIR / "static" / "frontend" / ".vite" / "manifest.json",
    }
}

FRONTEND_URL = os.getenv("FRONTEND_URL")

if not FRONTEND_URL:
    FRONTEND_URL = "http://localhost"

    if is_vite_running():
        FRONTEND_URL = f"{FRONTEND_URL}:5173"
        print("Vite status: Vite server is running!", file=sys.stderr)
    else:
        FRONTEND_URL = f"{FRONTEND_URL}:8000"
        print("Vite status: Django serving React from static files", file=sys.stderr)


# Static files

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

STATIC_URL = "/static/"
STATICFILES_BASE = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    STATICFILES_BASE,
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Optionally, configure for error emails
ADMINS = [
    ("Admin", "admin@progressrpg.com")
]  # The emails to receive error notifications


LOGIN_REDIRECT_URL = "/"  # Or wherever you want to go after login
LOGIN_URL = "/login/"  # Customize the login URL

# Stripe
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

STRIPE_LIVE_MODE = STRIPE_SECRET_KEY.startswith("sk_live_")

# Canonical Stripe price IDs
STRIPE_PRICE_ID_PREMIUM_MONTHLY = os.getenv("STRIPE_PRICE_ID_PREMIUM_MONTHLY", "")
STRIPE_PRICE_ID_PREMIUM_ANNUAL = os.getenv("STRIPE_PRICE_ID_PREMIUM_ANNUAL", "")
STRIPE_PRICE_ID_FREE = os.getenv("STRIPE_PRICE_ID_FREE", "")

# Free-tier activity timer cap (seconds). Override via env var for local testing.
FREE_TIMER_LIMIT_SECONDS = int(os.getenv("FREE_TIMER_LIMIT_SECONDS", 1800))

# App URLs for Stripe redirects
STRIPE_SUCCESS_URL = os.getenv(
    "STRIPE_SUCCESS_URL",
    f"{FRONTEND_URL}/payment-success",
)
STRIPE_CANCEL_URL = os.getenv(
    "STRIPE_CANCEL_URL",
    f"{FRONTEND_URL}/payment-cancelled",
)
STRIPE_BILLING_RETURN_URL = os.getenv(
    "STRIPE_BILLING_RETURN_URL",
    f"{FRONTEND_URL}/account",
)

CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"

# Memory optimization settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch 1 task at a time (default is 4)
CELERY_WORKER_MAX_TASKS_PER_CHILD = (
    1000  # Restart worker process after 1000 tasks to free memory
)
CELERY_TASK_SOFT_TIME_LIMIT = 600  # 10 minutes soft limit (tasks should respect this)
CELERY_TASK_TIME_LIMIT = 900  # 15 minutes hard limit (task is killed)
CELERY_BROKER_POOL_LIMIT = 10  # Limit connection pool to reduce memory


EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in ("true", "1", "yes")

CF_TURNSTILE_SITE_KEY = os.getenv("CF_TURNSTILE_SITE_KEY")
VITE_TURNSTILE_SITE_KEY = CF_TURNSTILE_SITE_KEY
CF_TURNSTILE_SECRET_KEY = os.getenv("CF_TURNSTILE_SECRET_KEY")
CF_TURNSTILE_ENABLED = True
CF_TURNSTILE_VERIFY_IP = True
